### ISSUE TITLE
Any idea on how to reverse engineer their API?

### ISSUE THREAD

**Issue by kissu** [Scottapotamas/aputure-dmx-arduino#1]
You're by far the person who made the most progress on the topic of controlling Aputure lights with something else than the Sidus link app.
I know that this is a long shot but do you maybe have an idea on how to trigger any Amaran lights with some Streamdeck or API?
Tried to look for people who may have reverse-engineered the thing but had no success.
Also, Aputure doesn't seem to be cooperative on that topic either. 😒

**Comment by Scottapotamas** [comment]
I guess I'll ask some obvious questions - instead of reinventing the wheel, is some kind of IP-DMX adapter not suitable?

I know DMX support is only on some of the Amaran line of lights, so it's probably dependent? The MC Pro (and possibly some others) support CRMX and can act as a bridge to DMX I believe.

As a quick hack/alternative (and depending on your light(s)) you could pull apart one of their 2.4G basic remotes and either wire up something to the button pads, or look into reverse engineering that simpler wireless link.

While I'm certainly _capable_ of poking at their Bluetooth Mesh implementation, it's a lot of work and I've already got my plate full with other cinema-adjacent reverse engineering projects...

**Comment by kissu** [comment]
I'll probably buy the [Sidus Link Bridge](https://shop.aputure.com/products/sidus-link-bridge) and try to reverse engineer it with Wireshark. 🦈 
That way, it will be fully compatible with all of my lights (because I do indeed not have DMX on all of them).

Haha, no issues if you're already busy. 👌🏻 
Wish you a good day. 🙏🏻
